export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#eff4ff",
        "secondary-container": "#4069f2",
        "surface-container-high": "#dee9fc",
        "on-primary-fixed": "#0f0069",
        "tertiary": "#005338",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9ff",
        "primary-fixed": "#e2dfff",
        "outline": "#777587",
        "on-secondary-fixed-variant": "#0039b5",
        "secondary-fixed": "#dce1ff",
        "tertiary-fixed-dim": "#4edea3",
        "secondary": "#1d4ed8",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "tertiary-fixed": "#6ffbbe",
        "on-error-container": "#93000a",
        "primary": "#3525cd",
        "on-primary-fixed-variant": "#3323cc",
        "primary-fixed-dim": "#c3c0ff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-surface-variant": "#464555",
        "surface-dim": "#d0dbed",
        "on-primary-container": "#dad7ff",
        "tertiary-container": "#006e4b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#67f4b7",
        "surface-container": "#e6eeff",
        "primary-container": "#4f46e5",
        "surface": "#f8f9ff",
        "secondary-fixed-dim": "#b7c4ff",
        "on-surface": "#121c2a",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#005236",
        "on-background": "#121c2a",
        "outline-variant": "#c7c4d8",
        "surface-variant": "#d9e3f6",
        "surface-tint": "#4d44e3",
        "background": "#f8f9ff",
        "surface-container-highest": "#d9e3f6",
        "on-secondary-fixed": "#001551",
        "on-secondary-container": "#fffbff",
        "inverse-primary": "#c3c0ff",
        "inverse-on-surface": "#eaf1ff",
        "inverse-surface": "#27313f"
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '4px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        full: '9999px',
      },
      boxShadow: {
        card: '0 20px 40px -10px rgba(18,28,42,0.06)',
      }
    },
  },
  plugins: [],
}
